### ISSUE TITLE
No such file or directory + Two cmd-s

### ISSUE THREAD

**Issue by rwjb** [foreshadow/atom-python-run#10]
On pressing F5 or F6, **cmd will open twice** returning the following message in each, except with varying file names and times as appropriate, regardless of the file attempted to run.
```
python.exe: can't open file 'test.py': [Errno 2] No such file or directory

Process returned 2 (0x2)   execution time : 0.053 s
Press any key to continue . . .
```

**Comment by foreshadow** [comment]
@rwjb 
I cannot figure out what exactly leads to this error. I need to reproduce this bug before making changes. I am afraid of making new bugs if not.
If it is convienient, I want to know:
- the title of the cmd that created
- folder structure related to the file when error occurs, and absolute path of it 
- whether the two cmd opened one after another or at the same time (or you accidentally hit F5 or F6 twice)

**Comment by rwjb** [comment]
The bug has since been resolved, and I suspect it was the result of updating the package; once I restarted Atom, the error was gone. (Yes, yes, the age old 'did you try turning it off and on again?')

I believe the issue can be closed.

But since I did actually test those things at the time, in case it's useful... *I would emphasize that these are no longer true. The plugin appears to work flawlessly.*

* the title of the cmd that created
 * python.exe test.py
* folder structure related to the file when error occurs, and absolute path of it
 * Bug appeared when run from an unrelated dir, and when the target *.py was in the same dir as python.exe
* whether the two cmd opened one after another or at the same time (or you accidentally hit F5 or F6 twice)
 * Same time; dialog spawned by Atom made it clear that the program was saved, run, then saved and run a second time.

---

This is a joy to have added to Atom, thank you.

**Comment by lifeisamoive** [comment]
Does the path to the file must be absolute path when i read a file?
When I support a relative path like:
```
def readFile():
    path = 'res/test.txt'
    try:
        f = open(path, 'r')
        text = f.read()
    finally:
        if f:
            f.close()
    return text
print(readFile())
```
An error occurred.
But when I changed the path to absolute path, the error gone.
Why?

**Comment by foreshadow** [comment]
@lifeisamoive 
Relative path works in my place, see the image below.
(You can check for update of this plugin first.)
I wonder what exactly is the error that occurred, the title of cmd, and the file structure as mentioned in comments above.

![image](https://cloud.githubusercontent.com/assets/2712675/17924239/598b47d0-6a1a-11e6-87ff-4fd1af059c05.png)

**Comment by foreshadow** [comment]
It seems different computers' cwd varies.
I set the cwd in v0.5.2, where @lifeisamovie 's problem should be fixed.
Create new Issue if there are further problems.

**Comment by foreshadow** [comment]
See #12
