### ISSUE TITLE
[REPORT] bug with python3.7.0

### ISSUE THREAD

**Issue by RyanHawking** [foreshadow/atom-python-run#101]
Hello,

I installed atom-python-run on my editor and it seems that I have a bug.

When I start a python program from Atom with the F6 key, the console opens but closes immediately.

Yet my program works. I tested it out of Atom and it was working.

I tried to reinstall the package, reinstall python etc... but the problem persists.

**edit :**
OS : Windows 10 / 64
Python : 3.7.0 / 32

**Comment by CodLiver** [comment]
I am not sure if we have the same problem, but this happened. I updated some of my packages and I had the exact thing happened to me. (the package content was deleted and it says deprecated.)

Check if the package content still exists via package manager -> atom-python-run -> open full path(?)

After trying some methods, I solved it by downloading this repo and install it manually to recover the content. Now it works.

**Comment by swodig112** [comment]
Hello,
I had the same problem. That's not actually a problem. You can change the settings.
Press `Ctrl + ,` to open the settings. Go to the packages. Search "atom-python-run". Open its settings.
Then scroll down. There is an option "Pause (F6)". Check that box.
This solved my problem. I wish it works for you too.
