### ISSUE TITLE
error code when i press F5

### ISSUE THREAD

**Issue by LazaroProdigy1** [foreshadow/atom-python-run#107]
i type in a command as simple as print('hello') then press F5 to run and my computer says it cant find Python

**Comment by ghost** [comment]
I too am experiencing this issue. 
example code:
`name = John
print(name)`

I get the following error: "Windows cannot find 'python'. Make sure you typed the name correctly, and try again."

error occurs upon running the code.

running version 1.35.1 of Atom (latest) on Windows 10 version 1803

**Comment by vmbrink** [comment]
I am having the same issue, and I even added Python to both my user path and my system path environment variables and it's still not working

**Comment by ghost** [comment]
I seem to have fixed, I started by uninstalling everything (python and Atom)and then re-installing python to "C:\Python3.7". 
Not choosing quick install but manually selecting all the options and path. 

- Make sure you select the option to add "PATH" 

I tested by running 'python' in my command prompt to make sure it was found on my system and then installed Atom.
If I now press F5 it opens up the Python IDE and runs the script. 

I feel so dumb for not trying this sooner.
