### ISSUE TITLE
为什么注释里面有中文，运行的时候就报错？

### ISSUE THREAD

**Issue by SusanDeng** [foreshadow/atom-python-run#113]
只要注释里有中文就运行不了代码，报错。以下是报错内容，该如何解决？
  File "/Users/apple/Desktop/Shell/www/my_project.py", line 2
SyntaxError: Non-ASCII character '\xbb' in file /Users/apple/Desktop/Shell/www/my_project.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

这不是atom的设置问题，中文显示没问题，就是不能使用atom-python-run运行代码。但是去掉注释里的中文就没问题了。求解决办法！

**Comment by foreshadow** [comment]
你需要检查文件所用的编码。这也不是本插件的问题。请参考
[https://www.runoob.com/python/python-chinese-encoding.html](https://www.runoob.com/python/python-chinese-encoding.html)
