### ISSUE TITLE
Split view causes script run twice

### ISSUE THREAD

**Issue by Kylapaallikko** [foreshadow/atom-python-run#12]
Editor's split view causes python script run twice. This issue appeared on recent update (0.5.2)

**Comment by foreshadow** [comment]
Weird, I cannot reproduce this, show me a screenshot if it is convenient.
Besides, I am using `getActiveTextEditor()` and only one could be active and returned.
That means only one script will be run in one `atom-python-run: run` call as far as i am concerned.
`v0.5.2` merely has one line in addition which is to explicitly specify the `cwd`.

**Comment by Kylapaallikko** [comment]
Looks like bug resolved itself just by restarting Atom.

Bug started to happen just after updating package. Maybe some error within editor caused it..

**Comment by foreshadow** [comment]
I've found it that when the package updates, (in atom) `deactivate`and`activate` will be called.
In this way the function will be registered twice. So it will be triggered twice when the package updates.
I will fix it soon.

**Comment by foreshadow** [comment]
This bug is fixed locally, it will still occur in the process of updating current version.
So it is no use publishing the update now.
I will publish it along with other bug fixes.
This will not occur any more in the version **after the next**.
