### ISSUE TITLE
Annoying notifications

### ISSUE THREAD

**Issue by henrasj** [foreshadow/atom-python-run#13]
I find the "Saving" and "Running" notifications rather annoying. For some reason I can't close them, and I have to wait until they disappear by themselves. Decided to comment them out in atom-python-run.js
Would be nice if there was an option to disable them in settings.

**Comment by foreshadow** [comment]
Good idea, I will add this feature in few days. Thanks for your advice.

**Comment by foreshadow** [comment]
@henrasj 
Done. Try it. 
There seems to be a mistake that is the latest version should be `v0.6.0`, while in some page it is `v0.7.0`.
