### ISSUE TITLE
版本号是不是有问题？

### ISSUE THREAD

**Issue by supperllx** [foreshadow/atom-python-run#14]
atom上显示的是0.7.0，下载链接：https://www.atom.io/api/packages/atom-python-run/versions/0.7.0/tarball ，直接404 not found了
应该是0.6.0或者0.5.2吧

**Comment by foreshadow** [comment]
是的，应该是`v0.6.0`。publish的时候手滑取消了又来了个二连发，然后版本号就+0.2了。
我`git reset --hard`了也改不回来。我也不知道怎么办。
atom客户端里能安装/更新吗？

**Comment by foreshadow** [comment]
我unpublish了v0.7.0，现在应该好了

**Comment by supperllx** [comment]
嗯，已经好了，感谢你的插件！

**Comment by foreshadow** [comment]
=w=
