### ISSUE TITLE
Choosing the console to run a file

### ISSUE THREAD

**Issue by maleksware** [foreshadow/atom-python-run#140]
I am using Atom on Windows 10. When I run my code that contains emoji, it runs in `cmd` by default, that has some problems with Unicode. I think it will be cool to choose console type in settings (e.g. Windows Terminal or Bash), so it will be possible to customize console windows.

**Comment by EpicCodeWizard** [comment]
If you are still looking for an answer, I changed mine to bind `Command Prompt` to F5 and `Windows Terminal` to F6. It helps out a **lot**, reply to this comment if you would like the code.
P.S. I am working on a package version where you can pick the terminal. As every terminal has a different start command, it becomes confusing. Fortunately, `Command Prompt` (`cmd /c COMMAND`) and `Windows Terminal` (`wt COMMAND`) make it easy to execute a command on startup.
