### ISSUE TITLE
opens multiple instances of cmd prompt

### ISSUE THREAD

**Issue by melpomenex** [foreshadow/atom-python-run#15]
for some reason after I updated it opens multiple instances of cmd prompt when I run a python script

**Comment by foreshadow** [comment]
Try restart the atom and see whether this is still happening.

Many had reported this bug after updating.
I have no idea of how to fix it now.

**Comment by melpomenex** [comment]
Restarting Atom seems to have fixed the problem. Thank you.

**Comment by foreshadow** [comment]
See Issue #12
