### ISSUE TITLE
Ubuntu下可以运行么？

### ISSUE THREAD

**Issue by Fretice** [foreshadow/atom-python-run#19]
只看到写的是在WIn下，不知道Ubuntu下行不行

**Comment by foreshadow** [comment]
不行呀，用了很多windows特产:joy::joy::joy:，参考#18。

**Comment by noparkinghere** [comment]
这是我发现的第一个不能在atom for linux上面运行的插件。

**Comment by foreshadow** [comment]
我写的蠢呀:joy::joy::joy:

**Comment by Armour** [comment]
....... 下载完了发现- - 不能在mac上用 - -

**Comment by foreshadow** [comment]
据说新版可以了，有空试试呗。
