### ISSUE TITLE
Mac?

### ISSUE THREAD

**Issue by JonRoosevelt** [foreshadow/atom-python-run#20]
Any possibility of making this available for mac?

**Comment by foreshadow** [comment]
Quite low, see #18.

**Comment by Kee-Wang** [comment]
Hi, you might need run-in-terminal. See issues here:

https://github.com/pohmelie/run-in-terminal/issues/10

**Comment by JonRoosevelt** [comment]
I'm sorry for the duplicate. Thank for the reply

**Comment by foreshadow** [comment]
It doesn't matter, just a implicit duplicate anyway.
