### ISSUE TITLE
Program runs in unexpected location

### ISSUE THREAD

**Issue by rwjb** [foreshadow/atom-python-run#21]
When running programs, they do not run locally. On my machine, the following program reports that it runs from my Downloads folder, rather than the project folder.
```
from os import getcwd
print(getcwd())
```
Can anyone reproduce?

**Comment by foreshadow** [comment]
Is the 

> my Downloads folder

irrelevant to your project?

Strictly speaking, according to the current version of this package, the program's cwd will be set to where the .py file located, rather than the project folder.

Anyway, in my place, the cwd is always what I expected.

**Comment by rwjb** [comment]
To clarify; the program is not running where it's located. The program is on a different disk than my downloads folder.

**Comment by foreshadow** [comment]
I tried again, but failed to reproduce it.
If you are familiar with `node.js`, you can inspect this package's source file, it is not long.

**Comment by Jaydosu** [comment]
very recently, it has become apparent that i am experiencing the same problem as @rwjb. before yesterday,  the python console ran from inside the same folder as my file, but it has now changed to my Documents.

is there anything or any way i can help?

**Comment by rwjb** [comment]
I can no longer reproduce this issue, and couldn't find anything in the source that I found suspect.

Cheers.
