### ISSUE TITLE
settings for the running command(s)

### ISSUE THREAD

**Issue by loserock** [foreshadow/atom-python-run#22]
The running command could be configurable.
For example, use the `pypy.exe` instead of `python.exe`.

There could be two different setups for the different function keys (F5 and F6). I can imagine something like this for F6:
```
python.exe -O -m compileall ./{FILENAME}.py
python.exe {FILENAME}.pyo
```

**Comment by foreshadow** [comment]
Good idea, I plan to add this future.
However, my examinations are approaching, so maybe I will do this in late January.

**Comment by foreshadow** [comment]
@loserock
I published v0.7.1, try it.
I have not tried multiple commands. And it is a little bit difficult to handle the order of the commands.
You can try `&&` connector in settings, but I don't promise it work correctly with multiple commands.
(As far as I tested, it doesn't. I am leaving these to the next version.)

**Comment by loserock** [comment]
Thanks!
Basically, it works, the && connector also works.
Two small notes:
 - The {file} tag cannot be used as the filename without the extension (like {file}.pyc or {file}.pyo form).
 - This is a Windows Atom package, however I tried to use it with Win10 WSL's bash (e.x.: "bash.exe -c python {file}"). It doesn't work ("'bash' is not recognized as an internal or external command...", even with full path call like C:\Windows\System32\bash.exe), but it works for me with Cygwin's bash (and it's Python)!

**Comment by foreshadow** [comment]
The version v0.7.3 is published.
`{dir}` `{name}` `{ext}` is now supported.
You can use `python.exe "{dir}\{name}{ext}"`, which is equal to `python.exe "{file}"`.

**Comment by h4wwk3ye** [comment]
Can anyone help me to assign f6 to pypy3. I tried pypy3 {file} and pypy3.exe{file} but pypy3 {file} was using python and with pypy3.exe the console automatically closes. I'm using windows.
