### ISSUE TITLE
能不能换成powershell运行

### ISSUE THREAD

**Issue by techstay** [foreshadow/atom-python-run#28]
CMD不太好看

**Comment by foreshadow** [comment]
好呀好呀，有空就改。
这段时间忙期中考试ORZ

**Comment by techstay** [comment]
等不到你，我自己做了一个 https://github.com/techstay/run-python-simply

**Comment by foreshadow** [comment]
又多了一个竞争对手:joy::joy::joy:

**Comment by techstay** [comment]
![滑稽](https://img.moegirl.org/common/thumb/7/71/%E6%BB%91%E7%A8%BD%E8%A1%A8%E6%83%85.jpg/250px-%E6%BB%91%E7%A8%BD%E8%A1%A8%E6%83%85.jpg)

**Comment by foreshadow** [comment]
Readme都抄的我的。。
话说你那个powershell也没比调过字体的cmd好看多少吧= =

**Comment by techstay** [comment]
多了一种选择嘛
