### ISSUE TITLE
*.pyw

### ISSUE THREAD

**Issue by rds92** [foreshadow/atom-python-run#29]
Is it possible to run ***.pyw** without console window?

in 

> atom-python-run.js 

 changes have been made to run, but it's still running via python.exe instead of pythonw.exe
```
...
if (info.ext != ".py" && info.ext != ".pyw") {
        notification("warning", format("{0} is not a .py file, exit.", [info.base]));
        return;
    }
...
f6_command: {
            title: "Command of F6",
            description: "{file} stands for current file path",
            type: "string",
            default: "pythonw.exe \"{file}\""
        }

```

**Comment by xovertheyearsx** [comment]
this shouldn't be an issue any more. you can tell `atom-python-run` to use `pythonw` instead of `python` from the settings panel.

**Comment by foreshadow** [comment]
Extension filter is added in v0.8.1.
