### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by merico** [foreshadow/atom-python-run#3]
Hi,

I don't think it works. At least pressing F6 doesn't do a thing and I can't find the package in ctrl+p either. Maybe you can help?

**Comment by foreshadow** [comment]
Fixed in latest version 0.3.0, try F5 or F6.

**Comment by iorbit** [comment]
Hitting F5 opens up a new window and then closes it the moment after.
I get no errors in the console

![python](https://cloud.githubusercontent.com/assets/17961817/16869834/080a57ee-4a7f-11e6-9b3a-c6cd946b54b7.jpg)

**Comment by foreshadow** [comment]
@iorbit It means that your program exited normally. To see your console output, you can add line
`raw_input()`
at the end of you code which means keeping waiting until you input something.

**Comment by sssurvey** [comment]
I think there is still a prolem with program quitting. I added 

> raw_input()

 then it still closes the window a moment after.
![image](https://cloud.githubusercontent.com/assets/2370877/16899514/9416c5da-4bcc-11e6-9be6-6c9688e5bb24.png)

**Comment by foreshadow** [comment]
@sssurvey That's a bug. In old version, any runtime error will kill the program immediately. Now I use a new console program in v0.4.0, which will always stop to show stdout/stderr after your program exits.
