### ISSUE TITLE
Launch Python via default command prompt (such as ConEmu/cmder)

### ISSUE THREAD

**Issue by astewartau** [foreshadow/atom-python-run#32]
I use [cmder](http://cmder.net/), which is a popular console emulator for Windows based on [ConEmu](http://conemu.github.io/). 

Currently, I am using cmder as my default command prompt - it normally opens instead of the ordinary Windows Command Prompt whenever I use an application that requires a prompt.

The only case where it doesn't launch by default is through atom-python-run - and this is what I see as an issue. Anyone know how this could be fixed?

**Comment by xovertheyearsx** [comment]
You can do this now, we'll probably need to add a front-end feature for ease of use.

You can change the terminal and it's exection option from within the atom-python-run module.

For now, you can do this as a quick hack.

1. Go to `%userprofile%\.atom\packages\atom-python-run\lib`
2. open the `atom-python-run.js` file
3. just before `terminal.type.spawns_tty` is called, add these lines.

```
terminal.type.has_a_tty.shell = 'shell name goes here';
terminal.type.has_a_tty.option = [the execution option(s) here]
```

shell takes a single string as its value.
option takes an array of strings as its value.

for example, assuming that the execution option for `cmder` is `/!`

```
cmds = [log, options, nocp, ...cmds];
terminal.type.has_a_tty.shell = 'cmder';
terminal.type.has_a_tty.option = ['/!'];
let tty = terminal.type.spawns_tty(...cmds);
tty.unref();
```

hit save. if youre using Atom to edit the file, `ctrl + shift + F5` to reload atom.

it will use that shell from that point on.

**Comment by xovertheyearsx** [comment]
This is complete as of version `Prepare 0.9.2 release` . It should work as expected now.
