### ISSUE TITLE
Clearly im special.

### ISSUE THREAD

**Issue by azazal160** [foreshadow/atom-python-run#4]
Hey there I have installed atom then installed python had a box to install into path did that and tried running a bit of code in atom and it still wont work?? help please :)

**Comment by foreshadow** [comment]
@azazal160 More detail is needed. To use this package on windows platform, you just need to install and enable this package then press F5 or F6 in atom editor with a *.py file opened. So what happened after pressing F5 or F6, or what error was showed?

**Comment by foreshadow** [comment]
See #5
