### ISSUE TITLE
請教一下，有辦法呼叫 IDLE 並執行嗎

### ISSUE THREAD

**Issue by NatLee** [foreshadow/atom-python-run#42]
大神你好

我在設定的 Command 中輸入 `python -i "{file}"`
只要沒有英文以外的語言
跳出 cmd 並執行程式，一切都很完美

可是，遇到中文就會有亂碼問題了
我嘗試在那一行中輸入兩個指令 `chcp 65001 && python -i "{file}"`
但卻只會執行 `chcp 65001`

這時，我就想起 python 自帶的 IDLE
![image](https://user-images.githubusercontent.com/10178964/28592594-215db230-71bc-11e7-9928-8f836e261393.png)
它長得像這樣

於是我就在 command 中輸入 `python -m idlelib "{file}"`
以為它可以用 python shell 直接幫我執行 script ，結果並不然
它用 IDLE 開啟了我的檔案，我還得手動按 F5 執行 
我已經用 Atom 了，應該是不需要再開個 IDLE 才對_( : |

所以現在想到的兩種解決方法都卡在其中一步
1. 呼叫 cmd 時，可先用指令 chcp 65001 來解決中文亂碼（但指令沒辦法執行兩個）
2. 呼叫 IDLE 並直接使用 python shell 執行，也不會產生亂碼（但它只會幫你用 IDLE開檔，得手動 F5）

我的問題大概是這樣，想請教一下有什麼解法嗎

非常感謝 :)

**Comment by foreshadow** [comment]
直接在cmd中运行会有乱码吗？

我找到了一种方法，`start python -i {file}`。不过在我这里这样会产生额外的一个cmd窗口。
我正在开发新的版本，我会努力尝试找一下解决方案的。

**Comment by NatLee** [comment]
其實也不是亂碼，是 error
`UnicodeEncodeError: 'cp950' codec can't encode character '\u8c22' in position 0: illegal multibyte sequence`
大概像是這種

其實直接 `python -i "{file}"` 就不會多產生一個窗口了
只是依然 cp950

謝謝 :)

**Comment by foreshadow** [comment]
新版本(v0.8.1)发布了，试试 command = `pythonw C:\python27\Lib\idlelib\idle.pyw -r {file}`

**Comment by NatLee** [comment]
我有看到  謝謝:)

這樣子call IDLE似乎會比較好
`python -m idlelib "{file}"`

**Comment by NatLee** [comment]
`python -m idlelib {file}`
這樣好像比較好 👍
