### ISSUE TITLE
code execution problems after updating to 0.8.0

### ISSUE THREAD

**Issue by avbaker** [foreshadow/atom-python-run#44]
after updating from 7.4, when I press f5 to run the program a console window comes up then closes immediately.

There doesn't seem to be any error message in the window, it's just blank!

**Comment by foreshadow** [comment]
Find this file and show me the content.
`USERHOME /.atom/packages/atom-python-run/cp.log`

**Comment by fqwl** [comment]
在下更新后也遇到了同样的问题，这是我的cp.log文件
```
INFO: OS Type: win32
INFO: Version Info: v0.0.10
DEBUG: check_args(): index 0: arg: C:\Users\fqwl\.atom\packages\atom-python-run\cp\main.py
DEBUG: check_args(): index 1: arg: python3.exe
DEBUG: check_args(): index 2: arg: "E:\Py\7、用户输入和 while 循环\demo_confirmed_users.py"
DEBUG: get_arg(): current argument: python3.exe
DEBUG: get_arg(): current argument: python3.exe
DEBUG: shift(): index is now 1
DEBUG: get_arg(): current argument: "E:\Py\7、用户输入和 while 循环\demo_confirmed_users.py"
```

**Comment by avbaker** [comment]
there are no .log files in the directory!

[image: Inline images 1]

Alex Baker

**Comment by foreshadow** [comment]
The `cp` parser in v0.8 uses python2.
If the first `python` in your `PATH` is python3, I believe you will get an error.
To fix this, you can install python2 as your default `python` interpreter, or wait for the next version.
I will work on this problem with @xovertheyearsx soon.

**Comment by xovertheyearsx** [comment]
I'm not sure it is a python3 issue. If it was, python would've given an error and the window would have stayed open.

Can I see the atom console log?

ctrl + alt + i -> console (tab)

**Comment by Dragonfire3900** [comment]
I got this from the console once it was replicated: 
C:\Users\****\.atom\packages\atom-python-run\lib\terminal.js:153 platform: win32
has_a_tty:
	shell: C:\WINDOWS\system32\cmd.exe
	option: /c,start

C:\Users\****\.atom\packages\atom-python-run\lib\terminal.js:161 	call: python

C:\Users\****\.atom\packages\atom-python-run\lib\terminal.js:162 	script: C:\Users\****\.atom\packages\atom-python-run\cp\main.py

C:\Users\****\.atom\packages\atom-python-run\lib\terminal.js:164 spawn_tty:
	options:
{
    "cwd": "C:\\Tempfiles",
    "detached": true
}
	args: python,C:\Tempfiles\Test.py

C:\Users\****\.atom\packages\atom-python-run\lib\terminal.js:176 child process exited with code 0

**Comment by xovertheyearsx** [comment]
tricky, this will be fun. are you all using python3 as your default global python?

**Comment by xovertheyearsx** [comment]
foreshadow is right. you need to install latest python2 as global python for it to work. working on a fix ATM so people can avoid this requirement.

**Comment by Dragonfire3900** [comment]
Yes I am using python 3 as default

**Comment by xovertheyearsx** [comment]
Ya, I found the issue. I'll see if I can make a quick hotfix for this issue.

```
$ python3 parse.py python ~/documents/python/hello.py
Traceback (most recent call last):
  File "parse.py", line 247, in <module>
    for key, value in namespace.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by avbaker** [comment]
I can confirm I'm using python 3.

**Comment by xovertheyearsx** [comment]
I figured it out. Very frustrating, especially coming from python2.

You have to add a `.` to the module, regardless of whether or not it is relative or absolute.

I created the directory setup as follows.

    /main.py
    --/lib
      --/__init__.py
      --/mody.py
      --/modx.py

modx.py

    def does_something():
        return "I gave you this string."

mody.py

    from modx import does_something
    
    def loaded():
        string = does_something()
        print(string)

main.py

    from lib import mody
    
    mody.loaded()


when I execute main, this is what happens

    $ python main.py
    Traceback (most recent call last):
      File "main.py", line 2, in <module>
        from lib import mody
      File "/mnt/c/Users/Austin/Dropbox/Source/Python/virtualenviron/mock/package/lib/mody.py", line 1, in <module>
        from modx import does_something
    ImportError: No module named 'modx'

I ran 2to3, and the core output was this

    RefactoringTool: Refactored lib/mody.py
    --- lib/mody.py (original)
    +++ lib/mody.py (refactored)
    @@ -1,4 +1,4 @@
    -from modx import does_something
    +from .modx import does_something
    
     def loaded():
         string = does_something()
    RefactoringTool: Files that need to be modified:
    RefactoringTool: lib/modx.py
    RefactoringTool: lib/mody.py

I had to modify mody.py's import statement to fix it

    try:
        from modx import does_something
    except ImportError:
        from .modx import does_something
    
    
    def loaded():
        string = does_something()
        print(string)

Then I ran main.py again and got the expected output

    $ python main.py
    I gave you this string.

**Comment by Dragonfire3900** [comment]
Yeah that does solve the main issue. Thanks for the help! Though I did notice a separate issue. The metric of the total running time consistently displays zero. So that could be something else to look into

**Comment by xovertheyearsx** [comment]
I figured it out. Very frustrating, especially coming from python2.

You have to add a `.` to the module, regardless of whether or not it is relative or absolute.

I created the directory setup as follows.

    /main.py
    --/lib
      --/__init__.py
      --/mody.py
      --/modx.py

modx.py

    def does_something():
        return "I gave you this string."

mody.py

    from modx import does_something
    
    def loaded():
        string = does_something()
        print(string)

main.py

    from lib import mody
    
    mody.loaded()


when I execute main, this is what happens

    $ python main.py
    Traceback (most recent call last):
      File "main.py", line 2, in <module>
        from lib import mody
      File "/mnt/c/Users/Austin/Dropbox/Source/Python/virtualenviron/mock/package/lib/mody.py", line 1, in <module>
        from modx import does_something
    ImportError: No module named 'modx'

I ran 2to3, and the core output was this

    RefactoringTool: Refactored lib/mody.py
    --- lib/mody.py (original)
    +++ lib/mody.py (refactored)
    @@ -1,4 +1,4 @@
    -from modx import does_something
    +from .modx import does_something
    
     def loaded():
         string = does_something()
    RefactoringTool: Files that need to be modified:
    RefactoringTool: lib/modx.py
    RefactoringTool: lib/mody.py

I had to modify mody.py's import statement to fix it

    try:
        from modx import does_something
    except ImportError:
        from .modx import does_something
    
    
    def loaded():
        string = does_something()
        print(string)

Then I ran main.py again and got the expected output

    $ python main.py
    I gave you this string.

**Comment by xovertheyearsx** [comment]
> Yeah that does solve the main issue. Thanks for the help! Though I did notice a separate issue. The metric of the total running time consistently displays zero. So that could be something else to look into

I saw that after I tested this solution. It has to do with the way I imported the timer. I'll see if I can add that to the hotfix.

**Comment by xovertheyearsx** [comment]
pulled and merged the hotfix. 

everyone using `python3` should be all set. the new version of `cp` is supposed to be compatible for both 2 and 3.

**Comment by xovertheyearsx** [comment]
> The metric of the total running time consistently displays zero. So that could be something else to look into

This issue was included in the hotfix. 

I also replaced `time.clock()` with `time.time()`; It should now show an approximate result of elapsed time as well. `time.time()` seems to be slightly more accurate than `time.clock()`.

**Comment by foreshadow** [comment]
The version v0.8.1 has been published.

**Comment by foreshadow** [comment]
@xovertheyearsx 
Althrogh you set the precision of time elapsed to 6, the last 3 digits is always `000` in my Win7 Ultimate.
I prefer 3-digit precision anyway. Maybe we can add an option.

**Comment by xovertheyearsx** [comment]
@foreshadow Sounds good. On my Win 10 Pro, it varies. I'm not sure why either, probably how Windows handles those functions internally or something?

**Comment by avbaker** [comment]
Using 0.8.1 has fixed the problem for me. Thanks a lot guys!

**Comment by Vasco10** [comment]
Here is the same: Wanted to prepare for a course this weekend - doesn't work (updated today):
The console closes immediately after F5.
Checked for the cp.log, but there was none (.atom/packages/atom-python-run/cp.log)

**Comment by xovertheyearsx** [comment]
atom console log please (after replicating issue). 

also, please verify the version you are using (atom-python-run package version).

0.8.1 has fixes for compatibility with python 2 and 3.

**Comment by Vasco10** [comment]
atom-python-run 0.8.1

the cp log is inexistent

**Comment by xovertheyearsx** [comment]
How to access Atoms Console Log

    Windows/Linux
        Ctrl + Shift + I
    Mac OS X
        Cmd + Alt + I
    Copy and paste the console output along with your post.

**Comment by Vasco10** [comment]
by doing on Windows 10 the  Ctrl + Shift + I
I get, see picture
![atom](https://user-images.githubusercontent.com/29803730/29191533-5e742726-7e1e-11e7-81a7-f5379253bfde.jpg)

**Comment by xovertheyearsx** [comment]
click the console tab. it will show you the output.

**Comment by Vasco10** [comment]
E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:153 platform: win32
has_a_tty:
	shell: C:\Windows\system32\cmd.exe
	option: /c,start

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:161 	call: python

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:162 	script: C:\Users\Vasco\.atom\packages\atom-python-run\cp\main.py

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:164 spawn_tty:
	options:
{
    "cwd": "E:\\Python_Repos\\Beginners_English",
    "detached": true
}
	args: python,E:\Python_Repos\Beginners_English\Basic_Ex1_Print_String.py

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:176 child process exited with code 0

**Comment by xovertheyearsx** [comment]
if you `ctrl+r`

then type `cmd` in the field and press `enter` or click `ok`

then at the prompt,

`> set | find /I "path"`

or

`> python -V` [press enter]

what does it say?

**Comment by Vasco10** [comment]
it says:

python -V --> Python 3.6.2 :: Anaconda custom (64-bit)

**Comment by Vasco10** [comment]
I don't know if this of interest:

E:\Anaconda3;
E:\Anaconda3\Library\mingw-w64\bin;
E:\Anaconda3\Library\usr\bin;
E:\Anaconda3\Library\bin;
E:\Anaconda3\Scripts

**Comment by xovertheyearsx** [comment]
we've tested with vanilla python, not anaconda. i'm honestly not sure if that has anything to do with it. 

i'm sick right now, otherwise i would test it right away. i just happened to be online (literally was about to close my browser) when i saw your notification. 

i know that anaconda is more of a software suite that includes packages like scikit and the like. basically, a quick and easy install. 

i'm using win 10 pro with latest updates and it's working fine with both python 2 and 3. although, they're vanilla installs.

it's in your path, atom seems to pass it to `cp`, but it gets lost somewhere in between and i'm very spacey right now. i'll take a deeper look later. sorry i couldnt provide any immediate help. my hunch would be it has something to do with anaconda (although that's a big maybe). 

hopefully @foreshadow will have better insight.

**Comment by Vasco10** [comment]
But it worked perfectly since already over a month, until an update was displayed.

**Comment by Vasco10** [comment]
If nobody can't fix until tomorrow, I will install Visual Studio 2017.
Thanks anyway. Get better.

**Comment by xovertheyearsx** [comment]
that's even more interesting then. 

we ported `cp` from C/C++ to Python for portability and  modularity. it also allowed us to implement some extra features. basically, it's not using the executable anymore which we deprecated in v0.8.0. its now executing directly through python.

if you want, you can play around with it and test it and let us know what you find. 

the `cp` module is located in the atom-python-run package. `%userprofile%\.atom\packages\atom-python-run\cp` and you can execute it using your `python` interpreter. maybe that will help isolate the issue.

and thank you, i'm doing my best. although, im pretty sure i just need a bit more rest. good luck with your course!

**Comment by Vasco10** [comment]
Just saw your post, tried it. Here is the log (I don't know if you need it):

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:153 platform: win32
has_a_tty:
	shell: C:\Windows\system32\cmd.exe
	option: /c,start

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:161 	call: python

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:162 	script: C:\Users\Vasco\.atom\packages\atom-python-run\cp\main.py

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:164 spawn_tty:
	options:
{
    "cwd": "E:\\AtomStudio\\Data\\atom\\packages\\atom-python-run\\cp",
    "detached": true
}
	args: python,E:\AtomStudio\Data\atom\packages\atom-python-run\cp\main.py

E:\AtomStudio\Data\atom\packages\atom-python-run\lib\terminal.js:176 child process exited with code 0

**Comment by xovertheyearsx** [comment]
@Vasco10 

some of the paths were hard coded where it was necessary. 

for example, there's no default OS PATH for Atom. we expect Atom to be in the default directory which is, for Windows anyways, `%userprofile%\.atom` and `%localuserdata%\atom`. 

for example: `c:\users\username\.atom` and `c:\users\username\appdata\local\atom` are where we expect Atom to be available.

This tells me you don't have a default Atom installation.

for example, `E:\AtomStudio\Data\atom\packages\atom-python-run\` will fail because `atom-python-run` expects the `cp` module to be in `C:\Users\YourUserNameHere\.atom\packages\atom-python-run\cp`. 

that's also why you don't have a log. by default, if `cp` somehow executes, it will attempt to create a log from the current working directory. 

my best guess is that Atom attempts to execute it and `cmd` says it fails and then closes the window because there's nothing happening aside from the error message.

You'll have to modify some of the source to make it work with your current installation.

**Comment by xovertheyearsx** [comment]
perhaps the solution to this problem would be to use relative paths. not absolute ones. 

i could make a patch that sets it so the paths are relative and no longer absolute, but you would have to test it after the patch makes it upstream. it's the only way to know for sure.

this is code from the `cp\cp\cplib.py` that helps set the log path. if the path can't be determined, it creates a log in the current working directory.
```
def set_log_path():
    if 'win32' == platform:
        log = "{}\\.atom\\packages\\atom-python-run\\cp.log".format(environ['USERPROFILE'])
    else:
        log = "{}/.atom/packages/atom-python-run/cp.log".format(environ['HOME'])
    path = dirname(log)
    if not isdir(path):
        return "cp.log"
    return log
```

`lib\terminal.js` sets the default shell and the path to `cp\main.py`
```
let Win32TTY = function() {
    // windows xp and up can be gaurenteed to have the cmd.exe shell.
    // %comspec% should default to %windir%\system32\cmd.exe unless
    // otherwise modified by the end user.
    // https://en.wikipedia.org/wiki/Environment_variable#Windows
    this.shell = process.env.COMSPEC;
    this.option = ['/c', 'start'];
    this.call = 'python';
    this.script = `${process.env.USERPROFILE}\\.atom\\packages\\atom-python-run\\cp\\main.py`;
};
```

since the path `${process.env.USERPROFILE}\\.atom\\packages\\atom-python-run\\cp\\main.py` doesn't exist, cmd spits out an error saying it can't find the path and closes the running instance.

**Comment by foreshadow** [comment]
I am sorry to hear that, you can also try cloning a older version to your `atom/packages`.
SSH `git clone --branch v0.7.3 git@github.com:foreshadow/atom-python-run.git`, or
HTTPS `git clone --branch v0.7.3 https://github.com/foreshadow/atom-python-run.git`.
And, DON'T update it.
I am trying to fix this. But it may cost days.

**Comment by Vasco10** [comment]
Thanks for your help.
I chose Atom and its packageas due to its portability. I used for some time Visual Studio to code in Python. About 2 to 3 months ago, I wanted to try Atom (nice, simple, and most important its portability) and the module 'atom-python-run' which by the way worked perfectly before this new update 0.8.1

**Comment by Vasco10** [comment]
Thanks @foreshadow for this info. It works again, of course with the old version.

For those who don't know how to do it:
1. download from: https://libraries.io/atom/atom-python-run/0.7.3
2. unzip twice, the *.tar.gz, then *.tar (use 7-Zip)
3. dive into the folders until you reach this one "foreshadow-atom-python-run-d00c5d2"
4. Open it, select all what's in it, copy
5. Open Atom | File | Settings
6. click packages on your left
7. filter "atom-python-run"
8. uninstall the buggy version
9. Open File Explorer
10. Go to the default location C:\Users\name\AppData\Local\atom\packages\atom-python-run
11. Paste all the files that you copied on point 4, and replace any file the system asks you to replace
12. Restart your Atom
13. It works (at least for me)

Maybe there is another better method.

**Comment by xovertheyearsx** [comment]
it shouldn't take days... for `terminal.js` we can just mod it to reflect a portion of code that used to work, which was originally relative. 

i just happened to make it absolute since Atom usually installs itself. on the off chance a user does a custom installation, that's where relative paths will fix this issue.

`__dirname + "/../bin/cp.exe"` was the original path to execute cp. just change the snippet to reflect that.

```
let Win32TTY = function() {
    // windows xp and up can be gaurenteed to have the cmd.exe shell.
    // %comspec% should default to %windir%\system32\cmd.exe unless
    // otherwise modified by the end user.
    // https://en.wikipedia.org/wiki/Environment_variable#Windows
    this.shell = process.env.COMSPEC;
    this.option = ['/c', 'start'];
    this.call = 'python';
    this.script = `${process.env.USERPROFILE}\\.atom\\packages\\atom-python-run\\cp\\main.py`;
};
```

changes to


```
let Win32TTY = function() {
    // windows xp and up can be gaurenteed to have the cmd.exe shell.
    // %comspec% should default to %windir%\system32\cmd.exe unless
    // otherwise modified by the end user.
    // https://en.wikipedia.org/wiki/Environment_variable#Windows
    this.shell = process.env.COMSPEC;
    this.option = ['/c', 'start'];
    this.call = 'python';
    this.script = `${__dirpath}\\..\\cp\\main.py`;
};
```

as for `cp` and its log, same idea, just a different way of doing it. figure out it's current working directory, usually a variable to handle this like `__dirname` in Atom. I'm sure `os.environ` has something in there.
