### ISSUE TITLE
Does not work on new laptop

### ISSUE THREAD

**Issue by BananaCEO** [foreshadow/atom-python-run#47]
Hi,
I use this add-on extensively on my main tower PC, yet on a new laptop i recently purchased, this add-on will now work. Once F5/F6 is pressed an error message pops up as follows:

> "Windows_ can not find 'python'. Make sure you typed the name correctly, and then try again"

I have installed python in the laptop, yet this error still occurs.

Looking forward to hearing back soon,
John Fletcher

**Comment by xovertheyearsx** [comment]
When you installed python, did you check off the option for adding it to your PATH variable during the installation?

**Comment by BananaCEO** [comment]
I simply reinstalled python and ticked the box, glad it's fixed now. Thank you, and keep up the good work!
