### ISSUE TITLE
Can't have atom-python-run run properly

### ISSUE THREAD

**Issue by fredericpv8** [foreshadow/atom-python-run#49]
Hi,
I searched the web and tried many things before contacting you..

Even though I change "F5 command" to "python3 {file}" I can't seem to have it working properly.

When hitting F5, I get the attached message in the terminal.

I can have Geany working properly with python3. But I would rather be using Atom with your package.
![image](https://user-images.githubusercontent.com/32399250/31030293-1d21f83a-a555-11e7-98bb-54b29f1e30de.png)

Anything you can do will be most welcomed.

Thanks,
Frederic

**Comment by xovertheyearsx** [comment]
Hi Frederic, can you reproduce the error and get `atom`s console output?

In `atom`, press `Cmd` + `Alt` + `I`. In the `pane` that opens, you'll see `tab`s. One of the `tab`s says `console`. Click on it, reproduce the error and watch the `output`. Copy and paste that `output` here so I can get some extra details on how the command is being passed to `cp`.

I'll try to reproduce the error my self afterwards when I have some time.

**Comment by fredericpv8** [comment]
Hi Austin,

Thanks a lot for the quick response.

Here is the requested information.

Looks like python3 is called for my script (hello_world, yeah... ;-) but 
not for main.py... :

platform: darwin
shell: osascript
option: -e
call: python
script: 
/Volumes/Frederic-HD/.atom/packages/atom-python-run/lib/../cp/main.py
command: tell app "Terminal" to do script "python 
/Volumes/Frederic-HD/.atom/packages/atom-python-run/lib/../cp/main.py 
python3 /Volumes/Frederic-HD/Documents/python_work/hello_world.py"
/Volumes/Frederic-HD/.atom/packages/atom-python-run/lib/terminal.js:227 
pause: true
pipeFile: false
pipePath:
log: true
args: python3,/Volumes/Frederic-HD/Documents/python_work/hello_world.py
options: {
     "cwd": "/Volumes/Frederic-HD/Documents/python_work",
     "detached": true
}







Austin wrote:

**Comment by xovertheyearsx** [comment]
Not a problem.

Sometimes there's a log file created in your package directory. If cp manages to execute anything, it will attempt to create the log first and write to the log until it fails.

If it exists (sometimes it is not created and will be missing) for you, that log can be found here: /Volumes/Frederic-HD/.atom/packages/atom-python-run/cp.log

you can use terminal to grab the output.

`cmd + space` to open the spotlight tool
type in `terminal` and hit `enter`
type into terminal `cat /Volumes/Frederic-HD/.atom/packages/atom-python-run/cp.log`

The way I usually do this is like this...

If the file does not exist, you'll see something similar to this

```
$ cat ~/.atom/packages/atom-python-run/cp.log 
cat: /home/th3ros/.atom/packages/atom-python-run/cp.log: No such file or directory
```

If the file does exist, you'll see something similar to this

**Comment by fredericpv8** [comment]
It looks like your message to me was truncated.

I did what you recommended and I get the "No such file of directory" 
message.

I am not sure what to do next...

Frederic




Austin wrote:

**Comment by fredericpv8** [comment]
Seems like the file does not exist :  I get this message : 
```
frederic$ cat /Volumes/Frederic-HD/.atom/packages/atom-python-run/cp.log
cat: /Volumes/Frederic-HD/.atom/packages/atom-python-run/cp.log: No such file or directory
```
Also:
```
frederic$ which python
/usr/bin/python
frederic$ which python3
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
frederic$ python -V
Python 2.7.10
frederic$ python3 -V
Python 3.6.2
```

**Comment by xovertheyearsx** [comment]
It's an operator bug. I patched it. All I have to do is push it to the repo. Once you see the update, let me know if it fixes the issue for you.

In the mean time, you can patch and test it your self if you're up to it. This is how.

On [line 59](https://github.com/foreshadow/atom-python-run/blob/master/cp/cp/parse.py#L59), you'll see a conditional statement that looks like this.

```
 def defaultLogPath(self):
        if 'win' in platform:  # this is line 59
            return "{}\\.atom\\packages\\atom-python-run\\cp.log".format(environ['USERPROFILE'])
        return "{}/.atom/packages/atom-python-run/cp.log".format(environ['HOME'])
```

Change it so that it looks like this.

```
 def defaultLogPath(self):
        if 'win32' == platform:  # this is the only line that gets modified
            return "{}\\.atom\\packages\\atom-python-run\\cp.log".format(environ['USERPROFILE'])
        return "{}/.atom/packages/atom-python-run/cp.log".format(environ['HOME'])
```

And that should fix the issue for you.

Let me know if you have any other problems or questions.

**Comment by fredericpv8** [comment]
I updated it and now I can see the change in line #59 of parse.py.

I do get another error now:

```
frederic$ python /Volumes/Frederic-HD/.atom/packages/atom-python-run/lib/../cp/main.py p y t h o n
Error: Expected optional option argument: got "n" instead 
```

**Comment by Troxi** [comment]
I am having the exact same issue too.

**Comment by xovertheyearsx** [comment]
I'm looking it to it. I was able to reproduce it and thanks your logs I'm able to verify the issue. I'm looking in to it during my spare time, so it might take me a little bit longer than usual. `darwin` platform has slightly different behavior.

For example. pausing on `darwin` doesn't matter. the `terminal` app will stay open regardless and display what commands were executed.

The `python` argument gets expanded in to `p y t h o n` which causes `cp` to think each letter is a separate argument and expects a `script` argument as its final argument, but receives `n` instead. 

Once I figure out why `python` gets expanded and why the `script` argument isn't passed along with the command string, I can resolve this issue.

The spacing I find strange and is definitely a bug. I'm in the middle of debugging the issue and I'll post the results when I'm ready with a solution. I'll push the patch through an update once it's ready.

**Comment by xovertheyearsx** [comment]
Pushed the patch to the repo. Should be all set now; Let me know how the darwin patch works out.

**Comment by fredericpv8** [comment]
I am still getting the same message. 

My log indeed shows the same thing as in your previous message.

**Comment by donq123** [comment]
I am also getting the same message

**Comment by xovertheyearsx** [comment]
Unfortunately, you will continue to experience issues with executing until the patch is pushed upstream.

If you're looking for a remedy until then. You can use the development version until this happens.

Open the `terminal` app with `cmd + space` and type in `terminal` in `spotlight` and hit `enter`.

In terminal, type in the following.
```
cd ~/Documents
apm uninstall atom-python-run
git clone https://github.com/foreshadow/atom-python-run.git
cd atom-python-run
git checkout darwin-patch
apm link
```

You should be all set from there. However, as a warning, I'm not sure if it'll update automatically after doing this. Which means you'll have to to undo all of this and restore it back to normal. This is easy.

```
cd ~/Documents/atom-python-run
apm unlink
cd ..
rm -rf atom-python-run/
apm install atom-python-run
```

I'll post here once @foreshadow pushes the update through.

**Comment by xovertheyearsx** [comment]
The patch has been pushed upstream and is now available. It should work as expected now with the `Prepare 0.9.2 release`.
