### ISSUE TITLE
I can't use this package 

### ISSUE THREAD

**Issue by Fillry** [foreshadow/atom-python-run#6]
when i press F5

it alert me " Windows cannot find ' C:\Users\Thanakit' "
My user account is Thanakit Khamhung

pls help

**Comment by foreshadow** [comment]
@Fillry 
Oops, I'm sorry for that. I used a wrong syntax in node.js which will split the path if it contains space.
I fixed it in v0.4.2. You can update the package and try it again. It should work fine now.
