### ISSUE TITLE
Change terminal to ConEmu on Windows 10

### ISSUE THREAD

**Issue by wickedjargon** [foreshadow/atom-python-run#77]
I have searched the documentation but cannot find the answer to this?

How can I force atom-python-run to use ConEmu (my alternative to Windows Command Prompt) on Windows 10?

I tried adding "ConEmu" to the `Terminal` field in Settings but had no luck. I tried a few other things like copy/pasting the path to its executable, still no luck

I even changed the default terminal on Windows 10 with these instructions here:
https://conemu.github.io/en/DefaultTerminal.html

still no luck, any suggestions?

**Comment by xovertheyearsx** [comment]
Added it to the [wiki](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#alternative-shells).
