### ISSUE TITLE
windows cannot find "python"

### ISSUE THREAD

**Issue by cameron1764** [foreshadow/atom-python-run#78]
when i press f5 it says this: 
![image](https://user-images.githubusercontent.com/21684311/37220902-f9926e60-23bf-11e8-955b-a6ecd3de0a50.png)

any help would mean a lot. Thanks

**Comment by foreshadow** [comment]
As what is said in [Prerequisite](https://github.com/foreshadow/atom-python-run#prerequisite), add the directory path of `python.exe` into `PATH`. You may search (how to set) `environment variable` `PATH` for more info. Some python installer may automatically do it for you if you checked that option.

**Comment by xovertheyearsx** [comment]
This is covered in the wiki under [12 How Do I Use atom-python-run](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#pre-install)
