### ISSUE TITLE
run in the same terminal

### ISSUE THREAD

**Issue by paul7Junior** [foreshadow/atom-python-run#80]
Hi,

Is it the normal behavior of the package to
open a new terminal each time one's press f5.

Or is there a way to keep the same terminal
for all the runs?

I tried to open a terminal in interactive mode 
but each time I compile the code, it open another 
terminal.

Thank you,
Junior

**Comment by xovertheyearsx** [comment]
Yes. That's normal. 

No, there is no way to change this behavior; you could always take a peek under the hood and tinker with the code to make it work.

To be honest, multiple instances has become an annoyance for me. Issue #75 seems to be a promising fix to this. There just isn't any active development towards that solution right now. 

Note that this would be mainly experimental and would create a dependency for this project. 

For now, every time `F5 ` or `F6` is executed, a new instance will always be created. 

It's finally stable (a few strange bugs aside) and I'm sure most users are accustomed to the way this package currently works. 

Creating a new branch will introduce new bugs and issues which can be troublesome... hence the idea to create an experimental branch (until it's stable; bugs and issues will happen regardless).

You can always help out. We could use it!
