### ISSUE TITLE
Terminal compatibility

### ISSUE THREAD

**Issue by Presmanes3** [foreshadow/atom-python-run#81]
Good evening, 

I am using Ubuntu 17.10 with GNOME 3.26.2. My default terminal is Tilix, my  *$SHELL* is */bin/zsh* and I had some problems while trying to run my python files with Tilix.

First I let the **Terminal Settings** in blank (default option). It showed me an error refered with *xterm* terminal :

![image](https://user-images.githubusercontent.com/30297802/38471868-7876c6d0-3b77-11e8-9dc8-b39f7e3c05c9.png)

Then I tried to put *"Tilix"* and *"tilix"*  in the **Terminal Settings** but it did not work, same error message appeared. 

By modifying the */atom-python-run/lib/terminal.js* file replacing **"null"** with **"tilix"** in the getSessionTerminal() function. Now it looks like this : 
![image](https://user-images.githubusercontent.com/30297802/38472123-554c2ea8-3b7b-11e8-8b29-df5f22de1b33.png)

Other way is to replace **"xterm"** with **"tilix"** in the getDesktopTerminal() function.

Thank you in advance for your time and your work.
Javier

**Comment by xovertheyearsx** [comment]
I think it's awesome that you're tinkering with the code! There is an easier method though... or should be at least.

In setting's you can change the terminal from there. It's in the [Wiki -> How Do I use atom-python-run -> Alternative Shells](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#alternative-shells) section.

Is there any way that I can improve the docs to help others and your self understand better?

In `Atom -> Settings -> atom-python-run -> Settings` there is an option called **Terminal**. You should be able to use [man tilix](https://www.mankier.com/1/tilix) to find out the execution option for tilix to launch a new window. It's usually `-e` or `-x` for most terminals on most distros.

Terminal -> `tilix, -e`

**Comment by Presmanes3** [comment]
Thank you!

I set the code that I modified to default values and I put instead what you told me in the option **Terminal**: 
`Terminal -> tilix, -e`

It worked perfectly! I knew there should be an easier way to make it work but I did not find it.

I have no idea about JS, but it was not difficult to tinker the code to make it work, I just had to know what I was looking for and try to change some values to make it work. I mean that your code is very clear and easy to understand. 

As I said, thank you for your time and work.
Javier

**Comment by xovertheyearsx** [comment]
Glad to hear it!

I did detail how [terminal.js](https://github.com/foreshadow/atom-python-run/wiki/08-How-does-terminal-work) works for others in the [Wiki](https://github.com/foreshadow/atom-python-run/wiki) if you're curious. It breaks down how it works step by step in a guide like fashion. 

You can always use MDN's [JavaScript Guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide) for anything that seems to be a bit unclear.

We can always use a bit of help with this project seeing as we work on it in our spare time. Let us know if you have any other questions, issues, or ideas.
