### ISSUE TITLE
Different OS issue

### ISSUE THREAD

**Issue by nrs2bear** [foreshadow/atom-python-run#86]
Hello sir,
My english is not good so forgive me about that.
I have 2 PCs, one is using windows os and the other is using ubuntu.
When I use your package to run python, the windows version runs fine but the ubuntu seems to have a problem.
Here are the pictures, the 1st one is running on windows, the 2nd is on ubuntu.
I'm looking forward to hearing back from you. 
![35128956_2094483454155092_8977113494163816448_n](https://user-images.githubusercontent.com/29760877/41811423-95844628-7739-11e8-9d46-fd2839b16711.png)
![screenshot from 2018-06-23 22-59-04](https://user-images.githubusercontent.com/29760877/41811429-a06c5170-7739-11e8-8111-aa38d6a88b73.png)

**Comment by foreshadow** [comment]
Maybe it is python2 versus python3, check your python version.

**Comment by nrs2bear** [comment]
I've edit your package setting from "python" to "python3" and it's working now, thank a lot sir.

**Comment by nrs2bear** [comment]
I've edit your package setting from "python" to "python3" and it's working now, thank a lot sir.
