### ISSUE TITLE
Run the python in directory name with space

### ISSUE THREAD

**Issue by mattivityroom** [foreshadow/atom-python-run#9]
@foreshadow 
I have an issue, when we have folder with a **_space_** and try to run it we have a message in terminal like this:
```
python.exe: can't open file 'D:\Workspace\Simple Python\': [Errno 2]
No such file or directory
```
My example  in my directory **_D:\Workspace\Simple Pyhton_**

**Comment by foreshadow** [comment]
Pretty wierd. It seems that i fixed it in v0.4.0, but in the later version v0.5.0 it occurs again. I am trying to fix it.

**Comment by foreshadow** [comment]
@mattivityroom The bug is fixed in v0.5.1, try it. Thanks for using.

**Comment by mattivityroom** [comment]
@foreshadow Thank you, It work now

**Comment by AlexOxorn** [comment]
I also am having trouble with spaces in in my directory.
I tried running a simple Hello world script, ~/Directory With Space/HW.py
however when I try running it I get the message
can't open file '/Users/**[username]**/Directory': [Errno 2] No such file or directory

**Comment by CarretillaRoja** [comment]
I also having the issue. Aton on MacOS High Sierra.

The error I get is:
python3: can't open file '/Users/erik/Library/Mobile': [Errno 2] No such file or directory

The file I try to run is:
/Users/erik/Library/Mobile\ Documents/com\~apple\~CloudDocs/test_3.py

Thanks.

**Comment by foreshadow** [comment]
The code has not been updated in the past nine to ten months. Could you please provide your atom version and package version? And what is your settings for `F5/6 Command`?

**UPD**: Actually it works fine with spaces in directory for a long time on my Windows platform.

**Comment by CarretillaRoja** [comment]
Last version of Atom and the package is 0.9.7.

I am on MacOS, not Windows. Thanks in advance.
