### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 2PoL** [foreshadow/atom-python-run#90]
The Honorable Author:
In the Mac version of Atom, this popped up when I tried to run a piece of code
`SyntaxError: Non-ASCII character '\xe5' in file /Users/infinite/Desktop/python学习/time.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`
But this code can run in Python's IDE
Why is this happening ?
Please tell me how to solve this question.
Thank you !

**Comment by foreshadow** [comment]
那可能是你的ide比较智能，但是按道理解释执行一个源代码文件时是需要显式声明字符编码的。见你的错误信息中提到的链接。

**Comment by ghost** [comment]
@foreshadow is right. Just follow the link and it'll tell you how to fix it. [PEP-0263](https://www.python.org/dev/peps/pep-0263/)

**Note** on Windows the default system encoding is ISO-8859. Most modern systems are UTF compliant, although you're more likely to see UTF on a *nix system by default and ISO on a Windows system by default. Python by default will recognize the source file as ASCII.

**Comment by 2PoL** [comment]
但是当我在源代码的第一行添加了
`# -*- coding: utf-8 -*- `
还是显示出了同样的问题。
我在windows系统用的好好的，但刚换成Mac系统就不能用了，好难受⁄(⁄ ⁄ ⁄ω⁄ ⁄ ⁄)⁄
