### ISSUE TITLE
Cannot use Python 3.7

### ISSUE THREAD

**Issue by Unactived** [foreshadow/atom-python-run#93]
I'm using atom-python-run version 0.9.7.

I was using Python 3.5 when I installed the package. When I installed python 3.6 I can't remember having any issue, the package directly used it. However I recently installed Python 3.7 the same way but I couldn't get the package to use it, it keeps using 3.6.

My 3.7 installation is correctly in the Path, and before other Python versions.
The command entered in the settings also don't seem to affect the package. I tried changing it to `PATH\TO\Python37\python.exe {file}` but launching kept using Python 3.6.

Closing files and restarting Atom didn't seem to do much more.

I'd appreciate any help as I find this package useful and currently need to use this Python's version.

**Comment by ghost** [comment]
We need a log to know why that's happening. You can find out how to get that information in the wiki. [Logs - console log](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#console-log)

**Comment by Unactived** [comment]
It's ok now. I think the cause may be having other Python 3.6 processes opened may block this. After having closed every python windows and also some applications it launched python 3.7 fine.
