### ISSUE TITLE
Conflict when programing in C

### ISSUE THREAD

**Issue by GabrielHMorales** [foreshadow/atom-python-run#96]
I'm having a problem trying to run C codes.
This is the package i have installed. 
https://github.com/kriscross07/atom-gpp-compiler
My code runned as soon as i unabled the python run package.

**Comment by ghost** [comment]
You need to compromise and change the mappings, or deal with the fact that they are mapped to the same keys. Not much we can do about that. You can either change the mapping for this package or the other. It's up to you.

**Comment by foreshadow** [comment]
Maybe you can bind keys specifically to some languages, see https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#selectors-and-custom-packages.
