### ISSUE TITLE
input() error

### ISSUE THREAD

**Issue by daron4ever** [foreshadow/atom-python-run#97]
Hi,

`myTime=input()
`
I have an error in the Terminal:
```
Traceback (most recent call last):
  File "/practice/time.py", line 4, in <module>
    myTime=input()
  File "<string>", line 1, in <module>
NameError: name 'time' is not defined
```
Please help!

**Comment by ghost** [comment]
[Official Python Tutorial](https://docs.python.org/3/tutorial/index.html)

[Official documentation for builtins](https://docs.python.org/3/library/functions.html)
